### PR TITLE
Add aliases to content pages

### PR DESCRIPTION
**Pull request by Dindihub**
Added aliases to content pages to cover issue https://github.com/Dindihub/docsy-tuf.io/issues/14

Please review @chalin

### CODE REVIEW

**Review by chalin — CHANGES_REQUESTED** [review]
Why is the docsy theme being updated? This shouldn't happen if you're working from `docsy` at HEAD.

Oh, it seems that you pushed directly to the `docsy` branch in your local repo. You need to create a branch with another name in your local repo, otherwise you'll lose access to the upstream `docsy`.

Please resubmit your PR, but do so from a local branch that has a name other than `docsy`.

Overall this PR seems ok, though I'll review it in more detail after.

**Comment by Dindihub** [comment]
> Why is the docsy theme being updated? This shouldn't happen if you're working from `docsy` at HEAD.
> 
> Oh, it seems that you pushed directly to the `docsy` branch in your local repo. You need to create a branch with another name in your local repo, otherwise you'll lose access to the upstream `docsy`.
> 
> Please resubmit your PR, but do so from a local branch that has a name other than `docsy`.
> 
> Overall this PR seems ok, though I'll review it in more detail after.

Makes sense. Is there any way I can reverse the update to the themes/docsy? It's now being tracked by all my branches now.

**Comment by chalin** [comment]
> @chalin Makes sense. Is there any way I can reverse the update to the themes/docsy? It's now being tracked by all my branches.

The problem isn't the Docsy theme commit -- the commit in this PR _is_ the correct commit. The problem is that this PR is showing a Docsy theme commit as a _change_. This is likely happening because you created this PR based on the `docsy` branch, but forgot to pull the latest commits first.

>> Please resubmit your PR, but do so from a local branch that has a name other than `docsy`.

The previous statement is important.

Note that before you create the new branch, refresh your local `docsy` branch using the commands I gave you the other day via https://cloud-native.slack.com/archives/C078K0K0KND/p1725496247026039?thread_ts=1725495858.968089&cid=C078K0K0KND, namely:

```
git fetch --all --prune --tags
git switch docsy
git rebase upstream/docsy
git push origin
```

(I get the impression that you might have done this already, because #77 seems to be ok -- i.e., not showing an update to the `docsy` theme.)

**Comment by Dindihub** [comment]
> > @chalin Makes sense. Is there any way I can reverse the update to the themes/docsy? It's now being tracked by all my branches.
> 
> The problem isn't the Docsy theme commit -- the commit in this PR _is_ the correct commit. The problem is that this PR is showing a Docsy theme commit as a _change_. This is likely happening because you created this PR based on the `docsy` branch, but forgot to pull the latest commits first.
> 
> > > Please resubmit your PR, but do so from a local branch that has a name other than `docsy`.
> 
> The previous statement is important.
> 
> Note that before you create the new branch, refresh your local `docsy` branch using the commands I gave you the other day via https://cloud-native.slack.com/archives/C078K0K0KND/p1725496247026039?thread_ts=1725495858.968089&cid=C078K0K0KND, namely:
> 
> ```
> git fetch --all --prune --tags
> git switch docsy
> git rebase upstream/docsy
> git push origin
> ```
> 
> (I get the impression that you might have done this already, because #77 seems to be ok -- i.e., not showing an update to the `docsy` theme.)

@chalin Right i did use those commands. Like you mentioned, problem was making commits on my local docsy branch . I'll resubmit the PR. Thanks

**Comment by chalin** [comment]
Closed by #78

**Pull request closed without merging**
